### ISSUE TITLE
Human crosstraining bug

### ISSUE THREAD

**Issue by ghost** [yrmvgh/yiufcrawl#5]
Windows tiles version 1.5.2b1-yiuf-4gc2bcc00e39

Human training ice, earth or air magic (but not fire) also gains bows XP http://prnt.sc/euhwam

**Comment by yrmvgh** [comment]
This sounds like a fallthrough error. Thanks for the report!

**Comment by yrmvgh** [comment]
[should be fixed!](https://github.com/yrmvgh/yiufcrawl/releases)
